/**
 * IBM Cloud Identity API
 * Use these API definitions to develop and integrate applications with the IBM Cloud Identity services such as authentication, customization, users and groups management, and others.  A new version of the API will be released if there are attributes that are removed or renamed. New resources, parameters, or attributes can be added without advance notice. When you use these APIs, ignore the unrecognized response parameters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Address { 
    /**
     * The city or locality component. Maximum length is 128 characters.
     */
    locality?: string;
    /**
     * The country name component. Maximum length is 128 characters.
     */
    country?: string;
    /**
     * The region. Maximum length is 128 characters.
     */
    region?: string;
    /**
     * The formatted value of the address. Maximum length is 500 characters.
     */
    formatted?: string;
    /**
     * Indicates whether this is address is the primary address for correspondence.
     */
    primary?: boolean;
    /**
     * The street address. Maximum length is 128 characters.
     */
    streetAddress?: string;
    /**
     * The postal code. Maximum length is 40 characters.
     */
    postalCode?: string;
    /**
     * A label that indicates the attribute's function; for example, \"work\" or \"home\".
     */
    type?: Address.TypeEnum;
}
export namespace Address {
    export type TypeEnum = 'work';
    export const TypeEnum = {
        Work: 'work' as TypeEnum
    };
}
