/**
 * IBM Cloud Identity API
 * Use these API definitions to develop and integrate applications with the IBM Cloud Identity services such as authentication, customization, users and groups management, and others.  A new version of the API will be released if there are attributes that are removed or renamed. New resources, parameters, or attributes can be added without advance notice. When you use these APIs, ignore the unrecognized response parameters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LinkedAccount { 
    /**
     * The realm name of the user's external account The maximum length, in combination with externalId, is 239 characters.
     */
    realm: string;
    /**
     * The ID of a user's external account The maximum length, in combination with realm, is 239 characters.
     */
    externalId: string;
}
