/**
 * IBM Cloud Identity API
 * Use these API definitions to develop and integrate applications with the IBM Cloud Identity services such as authentication, customization, users and groups management, and others.  A new version of the API will be released if there are attributes that are removed or renamed. New resources, parameters, or attributes can be added without advance notice. When you use these APIs, ignore the unrecognized response parameters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PhoneNumber { 
    /**
     * A label that indicates the attribute's function; for example, \"work\" or \"home\".
     */
    type: PhoneNumber.TypeEnum;
    /**
     * A list of phone numbers that are associated with the user. The value is be canonicalized by the service provider according to format in RFC3966, for example, \"tel:+1-201-555-0123\". Canonical type values are work, home, mobile, fax, and pager. Maximum length is 32 characters.
     */
    value: string;
}
export namespace PhoneNumber {
    export type TypeEnum = 'work' | 'home' | 'mobile' | 'pager' | 'fax';
    export const TypeEnum = {
        Work: 'work' as TypeEnum,
        Home: 'home' as TypeEnum,
        Mobile: 'mobile' as TypeEnum,
        Pager: 'pager' as TypeEnum,
        Fax: 'fax' as TypeEnum
    };
}
